### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/Gson;

### ISSUE THREAD

**Issue by Totonti** [Laerdal/Laerdal.Xamarin.Dfu#1]
Hi @framinosona ,

I am testing the nuget package version 0.2.1 in a Xamarin Forms project to perform FW update on a BLE device and when it tries to parse the zip file it gives the following error:

03-04 17:36:32.347 E/AndroidRuntime(10053): FATAL EXCEPTION: IntentService[DfuBaseService]
03-04 17:36:32.347 E/AndroidRuntime(10053): Process: com.lince.supratronik, PID: 10053
03-04 17:36:32.347 E/AndroidRuntime(10053): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/Gson;
03-04 17:36:32.347 E/AndroidRuntime(10053): 	at no.nordicsemi.android.dfu.internal.ArchiveInputStream.parseZip(ArchiveInputStream.java:368)
03-04 17:36:32.347 E/AndroidRuntime(10053): 	at no.nordicsemi.android.dfu.internal.ArchiveInputStream.<init>(ArchiveInputStream.java:142)
03-04 17:36:32.347 E/AndroidRuntime(10053): 	at no.nordicsemi.android.dfu.DfuBaseService.openInputStream(DfuBaseService.java:1457)
03-04 17:36:32.347 E/AndroidRuntime(10053): 	at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1195)
03-04 17:36:32.347 E/AndroidRuntime(10053): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
03-04 17:36:32.347 E/AndroidRuntime(10053): 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-04 17:36:32.347 E/AndroidRuntime(10053): 	at android.os.Looper.loop(Looper.java:214)
03-04 17:36:32.347 E/AndroidRuntime(10053): 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-04 17:36:32.347 E/AndroidRuntime(10053): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.Gson" on path: DexPathList[[zip file "/data/app/com.lince.supratronik-4AQCLX2tP7YDTEPNyUfEgA==/base.apk"],nativeLibraryDirectories=[/data/app/com.lince.supratronik-4AQCLX2tP7YDTEPNyUfEgA==/lib/arm64, /data/app/com.lince.supratronik-4AQCLX2tP7YDTEPNyUfEgA==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]

 I try this:
            DfuInstall = new DfuInstallation(deviceId, fichero.FullPath);
            DfuInstall.Start();

The truth is that I don't know if I am implementing it well.
Could you add a small example ?

Thank you very much
Maria

**Desktop (please complete the following information):**
 - OS: Windows  10
 - Visual Studio 2019 v16.8.6

**Smartphone (please complete the following information):**
 - Device: Pixel 3aXL
 - OS: Android 10

**Comment by framinosona** [comment]
Hi! Thanks for using it and for that log, it's my bad I forgot to send a file in it. I pushed a new version: 0.2.2: https://www.nuget.org/packages/Laerdal.Xamarin.Dfu/

Can you try it and tell me if it solves your issue?

Also, I think you're using it correctly yes, make sure to Listen or Bind on the .State .Progress .Duration etc. properties to know that it's working. Also there is Events.DfuMessageReceived and Events.DfuErrorOccured that are useful for nice Logs

**Comment by Totonti** [comment]
Thank you very much! 
I will test the version and let you know

**Comment by Totonti** [comment]
Hi @framinosona,

It's working now, thank you!

Now I have to implement the status of the update in the screen using the DFUinstallation properties and test the DFU proccess in iOS.

thanks 
Maria
